### ISSUE TITLE
As a developer I need a storage place for biotope photographs

### ISSUE THREAD

**Issue by paul-gilbertson** [jncc/marine-habitat-classification#16]

**Comment by owenboswarva** [comment]
Perhaps use Flickr? Natural England and EA maintain accounts.

While Flickr isn't a proper scientific photo library, it supports "machine tags" that can be constructed from specialised metadata so might be flexible enough.

IMO setting up a JNCC photo library would be worthwhile particularly if we have higher-resolution images we can make available. There aren't enough open sources of biodiversity photos at the moment, so could be popular.

(We would need to think about the licensing options as not all of the biotope photos are copyright JNCC.)

**Comment by CathyJinJNCC** [comment]
Created a WEB_PHOTO table which will store the links to the images once they've been hosted somewhere

**Comment by ulric-wilson** [comment]
Note that Graeme Duncan in investigating a marine photo library, initially based on the 40k images held from the MNCR.  It should include the photos for MHC although as Owen notes, some MHC photos are not from MNCR and a so licensing will need to be clarified.  Ideally the proposed catalogue would be able to hold all photos but only make certain ones downloadable at high res.  Not sure if Flickr can do that.

Marine photo catalogue won’t be ready any time soon so an in interim solution (online service or JNCC web server storage) will be required.

The images in the current catalogue could be reused as is in the short term

e.g. on the biotope page
http://jncc.defra.gov.uk/marine/biotopes/biotope.aspx?biotope=JNCCMNCR00000653

and the subsequent ‘biotope image’ page
http://jncc.defra.gov.uk/marine/biotopes/biotope_image.aspx?biotope=JNCCMNCR00000653&cd=0001&image=IMG0021.jpg

use links of the following form:
http://jncc.defra.gov.uk/marine/biotopes/images/0001/HIMG0021_thumb.jpg
http://jncc.defra.gov.uk/marine/biotopes/images/0001/HIMG0021_large.jpg

Note that ‘CD’ number in the file path and query string are required, not just the Biotope code, because when the images were processed programmatically to the two sizes used on the websites (thumb and large)  the original images scans were not unique – they were numbered as  IMG0001 on each CD, so CD number included to make the image uniquely identifiable.  This CD and IMG number are stored in Access DB.

Ulric Wilson
Acting Head of Data Services
Work ext: 6853

**Comment by CathyJinJNCC** [comment]
The MHC photos have been put into jncc.resourcespace.com
