### ISSUE TITLE
Show distribution map

### ISSUE THREAD

**Issue by paul-gilbertson** [jncc/marine-habitat-classification#7]

**Comment by helen-lillis** [comment]
Could you try shrinking the physical habitat description table, and enlarging the map? Maybe give them 50% of the width each?

**Comment by helen-lillis** [comment]
Could you make the yellow square in the legend bigger so that it is obvious that it is referring to polygon areas rather than points?

**Comment by helen-lillis** [comment]
Could you edit the legend/caption text as follows:
   [red point] Records used to define the biotope (core records)
   [light blue point] Other records assigned to this biotope, marked as 'certain'
   [dark blue point] Other records assigned to this biotope, marked as 'uncertain'
   [yellow square] Predicted extent of the level 3 (for sublittoral rock & deep sea) or 4 (for sublittoral sediment) habitat
   Point data based on records in the UK Marine Recorder Snapshot [same hyperlink]. Predicted habitat extent is from UKSeaMap [different hyperlink: http://jncc.defra.gov.uk/page-7354].

**Comment by helen-lillis** [comment]
Would it be possible to make it so that the legend/caption depends on the biotope? For all LR* and LS* codes we don't have any of the yellow 'predicted habitat extent' in the maps, so it would be good if, for these codes, two things were omitted: (a) the yellow square legend item, and (b) the last sentence "Predicted habitat extent is from UKSeaMap".

**Comment by CathyJinJNCC** [comment]
Deployed my changes, let me know if they're okay

**Comment by helen-lillis** [comment]
1. I'm happy with the new size of the map & physical description sections, but the legend is now sitting on top of the image (I'm using Chrome)
2. It doesn't seem like the yellow square/rectangle has got any bigger? It represents an area so needs to be larger than the circles (which represent point locations).
3. Thanks for editing the text, I'm happy with this.
4. I see that you have made the legend/caption conditional - thanks. But on the LR* and LS* biotopes it is using the yellow square to label uncertain records instead of the dark blue spot.

**Comment by CathyJinJNCC** [comment]
Suspect your browser is caching the old style, trying pressing Ctrl+F5 on the page?

**Comment by helen-lillis** [comment]
Oh yes - rookie mistake! It all looks perfect now, happy to sign-off :+1:

**Comment by CathyJinJNCC** [comment]
Excellent thanks :)
